version: "2.4"
services:
  garrysmod:
    image: zs
    build:
      context: ./src/garrysmod
      dockerfile: Dockerfile
    volumes:
      - ./src/garrysmod/cfg/server.cfg:/var/lib/steam/.steam/SteamApps/common/GarrysModDS/garrysmod/cfg/server.cfg:ro
      - ./src/garrysmod/gamemodes/zombiesurvival:/var/lib/steam/.steam/SteamApps/common/GarrysModDS/garrysmod/gamemodes/zombiesurvival:ro
    command:
      - -game garrysmod
      - -maxplayers 16
      - +gamemode zombiesurvival
      - +map gm_construct
      - +sv_setsteamaccount ${STEAM_GSLT}
    stdin_open: true
    tty: true

  awscli:
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - ZS_FASTDL_BUCKET
      - ZS_MAPS_BUCKET
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src
    entrypoint: bash
