version: "2.4"
services:
  database:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=zombiesurvival
      - POSTGRES_PASSWORD=zombiesurvival
      - POSTGRES_USER=zombiesurvival
    healthcheck:
      test: pg_isready -U zombiesurvival
      interval: 3s
      timeout: 3s
      retries: 3

  garrysmod:
    image: zs
    build:
      context: ./src/garrysmod
      dockerfile: Dockerfile
    volumes:
      - ./src/garrysmod/cfg/server.cfg:/var/lib/steam/.steam/SteamApps/common/GarrysModDS/garrysmod/cfg/server.cfg:ro
      - ./src/garrysmod/gamemodes/zombiesurvival:/var/lib/steam/.steam/SteamApps/common/GarrysModDS/garrysmod/gamemodes/zombiesurvival:ro
    depends_on:
      database:
        condition: service_healthy
    command:
      - -game garrysmod
      - -maxplayers 16
      - +gamemode zombiesurvival
      - +map gm_construct
      - +sv_setsteamaccount ${STEAM_GSLT}
    stdin_open: true
    tty: true

  lapis:
    image: lapis
    build:
      context: ./src/lapis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=zombiesurvival
      - POSTGRES_PASSWORD=zombiesurvival
      - POSTGRES_DB=zombiesurvival
      - PORT=8080
    depends_on:
      database:
        condition: service_healthy
    command:
    - server
    volumes:
      - ./src/lapis:/usr/local/src

  awscli:
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - ZS_FASTDL_BUCKET
      - ZS_MAPS_BUCKET
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src
    entrypoint: bash
